name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda
  - python=3.8
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - bioconda::viennarna=2.3.1=1
  - multiset
  - httplib2
  - ffmpeg
  - simplejson
  - distro
  - distance
  - editdistance
  - sphinx
  - sphinx_rtd_theme
  - mordred
  - plum-dispatch
