name: docs
channels:
    - conda-forge
    - bioconda
    - defaults
depedencies:
    - viennarna==2.4.15=py38h8162308_0
    - python=3.8
    - pip:
      - pandas
      - editdistance
      - enum-compat
      - plum-dispatch
